### ISSUE TITLE
Create docker images for 2.2.2 and 3.0.0

### ISSUE THREAD

**Issue by shntnu** [CellProfiler/distribution#10]
Do this once we have resolved #9

**Comment by mcquin** [comment]
@shntnu I just pushed the Docker image for 3.0.0, with some (mostly minor) changes to the Dockerfile which I will PR as part of #12. @AetherUnbound and I are working on pinning dependencies for stable (and subsequently releasing 2.2.2), which should simplify the Dockerfile further. We'll create the image once those changes are officially in.

@karhohs I know you were having some Java woes today. At your earliest convenience, could you please give this image a try and let me know how it works out for you? Thanks!
