### ISSUE TITLE
Suppress logging from s6 overlay

### ISSUE THREAD

**Issue by shntnu** [CellProfiler/distribution#9]
Worth reading this for background https://github.com/CellProfiler/docker/pull/12, specifically this
> We use s6-overlay to prevent the Linux zombie reaping problem instead of phusion-base-image since it's much more lightweight. This occurs when components of CellProfiler fail and don't get cleaned up properly (read more about it here: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/).

The Dockerfile does this

    # Fix init and zombie process reaping problems using s6 overlay
    ADD https://github.com/just-containers/s6-overlay/releases/download/v1.11.0.1/s6-overlay-amd64.tar.gz /tmp/
    RUN gunzip -c /tmp/s6-overlay-amd64.tar.gz | tar -xf - -C /

which results in this extra logging info: 

    [fix-attrs.d] applying owners & permissions fixes...
    [fix-attrs.d] 00-runscripts: applying...
    [fix-attrs.d] 00-runscripts: exited 0.
    [fix-attrs.d] done.
    [cont-init.d] executing container initialization scripts...
    [cont-init.d] done.
    [services.d] starting services
    [services.d] done.
    ...
    [cont-finish.d] executing container finish scripts...
    [cont-finish.d] done.
    [s6-finish] syncing disks.
    [s6-finish] sending all processes the TERM signal.
    [s6-finish] sending all processes the KILL signal and exiting.
    

It will be great if this can be suppressed somehow. This might provide some info on how to do this https://github.com/just-containers/s6-overlay. 

I tried

    docker run -e S6_LOGGING=1  cellprofiler:2.2.1

But it just hangs. 

I checked by setting `S6_LOGGING=0`

    docker run -e S6_LOGGING=0  cellprofiler:2.2.1

and that behaves as expected, i.e, its output is the same as

    docker run -e  cellprofiler:2.2.1

**Comment by shntnu** [comment]
`docker run -e S6_LOGGING=1 `... should do the trick

**Comment by shntnu** [comment]
Worth reading this for background https://github.com/CellProfiler/docker/pull/12

**Comment by shntnu** [comment]
@purohit I was wondering whether you have any experience with silencing s6 (see details above). It will be great to have your thoughts on this.

**Comment by purohit** [comment]
I haven't tried to silence s6, sorry -- in our logging, these logs are ones we definitely want to keep so we can debug if something has gone wrong.

**Comment by shntnu** [comment]
Ah ok - makes sense. 

To clarify, do you want the s6 logging in addition to the CellProfiler logging (I imagine they are separate, unless s6 somehow merges the two)?

The only issue I have is that the logging goes to stdout instead of stderr. And that causes problems because we sometimes pipe CellProfiler stdout to a file (e.g. https://github.com/CellProfiler/Distributed-CellProfiler/issues/52)

Thanks in any case! We'll see if we can get `S6_LOGGING` to work.

**Comment by purohit** [comment]
> do you want the s6 logging in addition to the CellProfiler logging

Yep.

> The only issue I have is that the logging goes to stdout instead of stderr. And that causes problems because we sometimes pipe CellProfiler stdout to a file

Yeah, that is annoying, although you can probably `grep` out what you don't need since it looks like there are just a handful of log prefixes (`fix-attrs.d`, etc).

**Comment by mcquin** [comment]
@shntnu I think that @purohit's suggestion that you can filter out logs you don't need is an entirely reasonable suggestion, given the standardized formatting. Is this something you can work with? If so, please close the issue. If not, let's continue to discuss!

**Comment by shntnu** [comment]
@mcquin It was likely a bug in the s6 version we were using. #11 fixes that.
